---
name: Trivy Scan
on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Security Scan
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          trivyignores: '.trivyignore'
